-- Insert complete policy data with all fields populated
-- Run this in MySQL: mysql -u root -p customerDB < policy_insert_data.sql

-- Policy 1: Life Insurance - Active
INSERT INTO POLICY (
    POLICY_NUMBER, EXT_POLICY_NUMBER, NI_NUMBER, TITLE, FORE_NAME, SUR_NAME,
    ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5, ADDRESS_LINE_6,
    POST_CODE, PRODUCT, VERSION, POLICY_STATUS, POL_STATUS_DESC, POL_SUSPENDED,
    GROUP_CHILD, GROUP_CHILD_AGENCY, POLICY_AGENCY, GROUP_PARENT,
    POL_START_DATE, POL_NPR_MATURITY_DATE, PR_MATURITY_DATE, NPR_ORIG_MAT_DTE, PR_ORIG_MAT_DTE, RENEWAL_DATE,
    SELF_EMPLOYED, PAYMENT_FREQ, PH_PAYMENT_METHOD, ACCOUNT_NUMBER, SORT_CODE,
    EMPLOYEE_REGULAR, SELF_EMP_REGULAR, THIRD_PARTY_REGULAR, PR_INDEX,
    PERSONAL_SINGLE, PERSONAL_VARIABLE, PERSONAL_WAIVER, EMPLOYER_REGULAR, EMPLOYER_SINGLE, EMPLOYER_VARIABLE, EMPLOYER_WAIVER,
    PP_STANDALONE_TI, PP_INTEGRATED_TI, PROTECTED_RIGHTS, NICO,
    TRANSFER_IN, TRANSFER_IN_INTERNAL, PR_TRANSFER_IN, PR_TRANSFER_IN_INTERNAL,
    PC_SGR, PC_SGR_INTERNAL, PC_NON_SGR, PC_NON_SGR_INTERNAL,
    STANDALONE_PHI_WAIVER, DRAWDOWN, INCREMENT_PROCESSED, DECREMENT_PROCESSED,
    PREMIUM_HOLIDAY_STARTED, PREMIUM_HOLIDAY_ENDED, SWITCH_PROCESSED, AUTOSWITCH_PROCESSED, REDIRECTION,
    PAF_FUND, WP_FUND, NON_PAF_WP_FUND, EXTERNAL_FUND, PHASED_SWI, SPP_LOYALTY_BONUS,
    LFR, ALFR, FBC, CAFCA_RDR, DATE_OF_BIRTH, SEX
) VALUES (
    'POL001', 'EXT-2024-001', 'AB123456C', 'Mr', 'John', 'Smith',
    '123 Main Street', 'London', 'Greater London', 'England', 'United Kingdom', '',
    'SW1A 1AA', 'Life Insurance', 1, 'ACTIVE', 'Policy is active and in good standing', 'N',
    'GRP001', 'Child Agency London', 'London Central Agency', 'Parent Group Ltd',
    '2020-01-15', '2040-01-15', '2040-01-15', '2040-01-15', '2040-01-15', '2025-01-15',
    'N', 'Monthly', 'Direct Debit', '12345678', '20-00-00',
    '250.00', '0.00', '0.00', 'INDEX_A',
    '0.00', '0.00', '0.00', '150.00', '0.00', '0.00', '100.00',
    'YES', 'NO', 'PR_YES', 'NICO123',
    '5000.00', 'N', '3000.00', 'N',
    '1000.00', 'Y', '500.00', 'N',
    'NO', 'NO', 'YES', 'NO',
    'NO', 'NO', 'NO', 'NO', 'NO',
    'FUND_A', 'WP_001', 'NON_PAF_001', 'EXT_001', 'NO', 'BONUS_100',
    'LFR_001', 'ALFR_001', 'FBC_001', 'CAFCA_001', '1980-05-20', 'M'
);

-- Policy 2: Health Insurance - Active
INSERT INTO POLICY (
    POLICY_NUMBER, EXT_POLICY_NUMBER, NI_NUMBER, TITLE, FORE_NAME, SUR_NAME,
    ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5, ADDRESS_LINE_6,
    POST_CODE, PRODUCT, VERSION, POLICY_STATUS, POL_STATUS_DESC, POL_SUSPENDED,
    GROUP_CHILD, GROUP_CHILD_AGENCY, POLICY_AGENCY, GROUP_PARENT,
    POL_START_DATE, POL_NPR_MATURITY_DATE, PR_MATURITY_DATE, NPR_ORIG_MAT_DTE, PR_ORIG_MAT_DTE, RENEWAL_DATE,
    SELF_EMPLOYED, PAYMENT_FREQ, PH_PAYMENT_METHOD, ACCOUNT_NUMBER, SORT_CODE,
    EMPLOYEE_REGULAR, SELF_EMP_REGULAR, THIRD_PARTY_REGULAR, PR_INDEX,
    PERSONAL_SINGLE, PERSONAL_VARIABLE, PERSONAL_WAIVER, EMPLOYER_REGULAR, EMPLOYER_SINGLE, EMPLOYER_VARIABLE, EMPLOYER_WAIVER,
    PP_STANDALONE_TI, PP_INTEGRATED_TI, PROTECTED_RIGHTS, NICO,
    TRANSFER_IN, TRANSFER_IN_INTERNAL, PR_TRANSFER_IN, PR_TRANSFER_IN_INTERNAL,
    PC_SGR, PC_SGR_INTERNAL, PC_NON_SGR, PC_NON_SGR_INTERNAL,
    STANDALONE_PHI_WAIVER, DRAWDOWN, INCREMENT_PROCESSED, DECREMENT_PROCESSED,
    PREMIUM_HOLIDAY_STARTED, PREMIUM_HOLIDAY_ENDED, SWITCH_PROCESSED, AUTOSWITCH_PROCESSED, REDIRECTION,
    PAF_FUND, WP_FUND, NON_PAF_WP_FUND, EXTERNAL_FUND, PHASED_SWI, SPP_LOYALTY_BONUS,
    LFR, ALFR, FBC, CAFCA_RDR, DATE_OF_BIRTH, SEX
) VALUES (
    'POL002', 'EXT-2024-002', 'CD789012E', 'Mrs', 'Jane', 'Doe',
    '456 Oak Avenue', 'Manchester', 'Greater Manchester', 'England', 'United Kingdom', '',
    'M1 2AB', 'Health Insurance', 2, 'ACTIVE', 'Health policy active with full coverage', 'N',
    'GRP002', 'Child Agency Manchester', 'Manchester Central Agency', 'Health Group Ltd',
    '2021-06-10', '2031-06-10', '2031-06-10', '2031-06-10', '2031-06-10', '2025-06-10',
    'N', 'Quarterly', 'Credit Card', '87654321', '40-00-01',
    '0.00', '0.00', '0.00', 'INDEX_B',
    '200.00', '50.00', '25.00', '0.00', '0.00', '0.00', '0.00',
    'NO', 'YES', 'PR_NO', 'NICO456',
    '0.00', 'N', '0.00', 'N',
    '0.00', 'N', '0.00', 'N',
    'YES', 'NO', 'NO', 'YES',
    'NO', 'NO', 'NO', 'NO', 'NO',
    'FUND_B', 'WP_002', 'NON_PAF_002', 'EXT_002', 'NO', 'BONUS_200',
    'LFR_002', 'ALFR_002', 'FBC_002', 'CAFCA_002', '1985-08-15', 'F'
);

-- Policy 3: Pension Plan - Pending
INSERT INTO POLICY (
    POLICY_NUMBER, EXT_POLICY_NUMBER, NI_NUMBER, TITLE, FORE_NAME, SUR_NAME,
    ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5, ADDRESS_LINE_6,
    POST_CODE, PRODUCT, VERSION, POLICY_STATUS, POL_STATUS_DESC, POL_SUSPENDED,
    GROUP_CHILD, GROUP_CHILD_AGENCY, POLICY_AGENCY, GROUP_PARENT,
    POL_START_DATE, POL_NPR_MATURITY_DATE, PR_MATURITY_DATE, NPR_ORIG_MAT_DTE, PR_ORIG_MAT_DTE, RENEWAL_DATE,
    SELF_EMPLOYED, PAYMENT_FREQ, PH_PAYMENT_METHOD, ACCOUNT_NUMBER, SORT_CODE,
    EMPLOYEE_REGULAR, SELF_EMP_REGULAR, THIRD_PARTY_REGULAR, PR_INDEX,
    PERSONAL_SINGLE, PERSONAL_VARIABLE, PERSONAL_WAIVER, EMPLOYER_REGULAR, EMPLOYER_SINGLE, EMPLOYER_VARIABLE, EMPLOYER_WAIVER,
    PP_STANDALONE_TI, PP_INTEGRATED_TI, PROTECTED_RIGHTS, NICO,
    TRANSFER_IN, TRANSFER_IN_INTERNAL, PR_TRANSFER_IN, PR_TRANSFER_IN_INTERNAL,
    PC_SGR, PC_SGR_INTERNAL, PC_NON_SGR, PC_NON_SGR_INTERNAL,
    STANDALONE_PHI_WAIVER, DRAWDOWN, INCREMENT_PROCESSED, DECREMENT_PROCESSED,
    PREMIUM_HOLIDAY_STARTED, PREMIUM_HOLIDAY_ENDED, SWITCH_PROCESSED, AUTOSWITCH_PROCESSED, REDIRECTION,
    PAF_FUND, WP_FUND, NON_PAF_WP_FUND, EXTERNAL_FUND, PHASED_SWI, SPP_LOYALTY_BONUS,
    LFR, ALFR, FBC, CAFCA_RDR, DATE_OF_BIRTH, SEX
) VALUES (
    'POL003', 'EXT-2024-003', 'EF345678G', 'Dr', 'Robert', 'Johnson',
    '789 Pine Road', 'Birmingham', 'West Midlands', 'England', 'United Kingdom', '',
    'B2 3CD', 'Pension Plan', 1, 'PENDING', 'Policy pending initial documentation review', 'N',
    'GRP003', 'Child Agency Birmingham', 'Birmingham Central Agency', 'Pension Group Ltd',
    '2024-03-01', '2054-03-01', '2054-03-01', '2054-03-01', '2054-03-01', '2025-03-01',
    'Y', 'Annual', 'Bank Transfer', '11223344', '60-00-02',
    '5000.00', '2000.00', '1000.00', 'INDEX_C',
    '0.00', '0.00', '0.00', '8000.00', '2000.00', '1000.00', '500.00',
    'YES', 'YES', 'PR_YES', 'NICO789',
    '50000.00', 'Y', '25000.00', 'Y',
    '15000.00', 'Y', '8000.00', 'Y',
    'NO', 'YES', 'NO', 'NO',
    'NO', 'NO', 'YES', 'YES', 'YES',
    'FUND_C', 'WP_003', 'NON_PAF_003', 'EXT_003', 'YES', 'BONUS_500',
    'LFR_003', 'ALFR_003', 'FBC_003', 'CAFCA_003', '1975-12-03', 'M'
);

-- Policy 4: Car Insurance - Suspended
INSERT INTO POLICY (
    POLICY_NUMBER, EXT_POLICY_NUMBER, NI_NUMBER, TITLE, FORE_NAME, SUR_NAME,
    ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, ADDRESS_LINE_4, ADDRESS_LINE_5, ADDRESS_LINE_6,
    POST_CODE, PRODUCT, VERSION, POLICY_STATUS, POL_STATUS_DESC, POL_SUSPENDED,
    GROUP_CHILD, GROUP_CHILD_AGENCY, POLICY_AGENCY, GROUP_PARENT,
    POL_START_DATE, POL_NPR_MATURITY_DATE, PR_MATURITY_DATE, NPR_ORIG_MAT_DTE, PR_ORIG_MAT_DTE, RENEWAL_DATE,
    SELF_EMPLOYED, PAYMENT_FREQ, PH_PAYMENT_METHOD, ACCOUNT_NUMBER, SORT_CODE,
    EMPLOYEE_REGULAR, SELF_EMP_REGULAR, THIRD_PARTY_REGULAR, PR_INDEX,
    PERSONAL_SINGLE, PERSONAL_VARIABLE, PERSONAL_WAIVER, EMPLOYER_REGULAR, EMPLOYER_SINGLE, EMPLOYER_VARIABLE, EMPLOYER_WAIVER,
    PP_STANDALONE_TI, PP_INTEGRATED_TI, PROTECTED_RIGHTS, NICO,
    TRANSFER_IN, TRANSFER_IN_INTERNAL, PR_TRANSFER_IN, PR_TRANSFER_IN_INTERNAL,
    PC_SGR, PC_SGR_INTERNAL, PC_NON_SGR, PC_NON_SGR_INTERNAL,
    STANDALONE_PHI_WAIVER, DRAWDOWN, INCREMENT_PROCESSED, DECREMENT_PROCESSED,
    PREMIUM_HOLIDAY_STARTED, PREMIUM_HOLIDAY_ENDED, SWITCH_PROCESSED, AUTOSWITCH_PROCESSED, REDIRECTION,
    PAF_FUND, WP_FUND, NON_PAF_WP_FUND, EXTERNAL_FUND, PHASED_SWI, SPP_LOYALTY_BONUS,
    LFR, ALFR, FBC, CAFCA_RDR, DATE_OF_BIRTH, SEX
) VALUES (
    'POL004', 'EXT-2024-004', 'GH901234I', 'Ms', 'Sarah', 'Williams',
    '321 Elm Street', 'Leeds', 'West Yorkshire', 'England', 'United Kingdom', '',
    'LS1 4EF', 'Car Insurance', 3, 'SUSPENDED', 'Policy suspended due to non-payment of premiums', 'Y',
    'GRP004', 'Child Agency Leeds', 'Leeds Central Agency', 'Auto Group Ltd',
    '2019-09-20', '2025-09-20', '2025-09-20', '2025-09-20', '2025-09-20', '2024-09-20',
    'N', 'Monthly', 'Direct Debit', '55667788', '80-00-03',
    '0.00', '0.00', '150.00', 'INDEX_D',
    '0.00', '0.00', '0.00', '0.00', '0.00', '0.00', '0.00',
    'NO', 'NO', 'PR_NO', 'NICO012',
    '0.00', 'N', '0.00', 'N',
    '0.00', 'N', '0.00', 'N',
    'NO', 'NO', 'NO', 'NO',
    'YES', 'YES', 'NO', 'NO', 'NO',
    'FUND_D', 'WP_004', 'NON_PAF_004', 'EXT_004', 'NO', 'BONUS_0',
    'LFR_004', 'ALFR_004', 'FBC_004', 'CAFCA_004', '1990-03-25', 'F'
);
